import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultConfig,migrateConfig,newRoom,appendPlayer,normalizeName,cleanItems,exportConfig,itemIds} from '../web/storage.js';
import {MANUAL_SCHEDULE,switchPlaylist,playlistState,restoreJournal,matchesActive} from '../web/logic.js';
import {mapPlaylist,publishRoom,cleanupRoom,deletionBlock,queueCleanup,protectedIds} from '../web/lifecycle.js';
import {normalizeBase,originPermission,fileKind,mediaUrl,assertReady,AnthiasApi} from '../web/api.js';
import {scanTargets,ipv4,ipString,scanPlayers,classifyResult,isAnthiasInfo} from '../web/discovery.js';
import {t,setLanguage} from '../web/i18n.js';
const copy=x=>structuredClone(x);
const file=(id,enabled=false,kind='image',order=0)=>({asset_id:id,name:id,uri:'/data/anthias_assets/'+id+(kind==='video'?'.mp4':'.png'),mimetype:kind,duration:kind==='video'?42:15,is_enabled:enabled,is_active:enabled,is_processing:false,is_reachable:true,play_order:order,...MANUAL_SCHEDULE,metadata:{}});
class API{
 constructor(){this.base='http://192.168.10.2';this.data=[file('h1',true),file('h2'),file('e1'),file('e2',false,'video'),file('next')];this.config={shuffle_playlist:false};this.calls=[];this.fail=null;this.controlFail=false;this.orderWrong=false;}
 async assets(){return copy(this.data);}
 async get(id){return copy(this.data.find(a=>a.asset_id===id));}
 async settings(){return copy(this.config);}
 async patchSettings(b){this.calls.push(['settings',copy(b)]);Object.assign(this.config,b);}
 async patch(id,b){this.calls.push(['patch',id,copy(b)]);if(this.fail===id){this.fail=null;throw new Error('Injected patch failure');}const a=this.data.find(a=>a.asset_id===id);Object.assign(a,b);a.is_active=a.is_enabled&&!a.is_processing;}
 async order(ids){this.calls.push(['order',copy(ids)]);if(!this.orderWrong)ids.forEach((id,i)=>{this.data.find(a=>a.asset_id===id).play_order=i;});else this.orderWrong=false;}
 async show(id){this.calls.push(['show',id]);if(this.controlFail)throw new Error('Control unavailable');}
 async remove(id){this.calls.push(['delete',id]);this.data=this.data.filter(a=>a.asset_id!==id);}
}
const createRoom=()=>{const r=newRoom('Conference room','192.168.10.2',1);r.playlists={home:[{id:'h1',duration:15}],event:[{id:'e1',duration:15},{id:'e2',duration:null}]};r.eventHistory=['e1','e2'];r.managedEventIds=['e1','e2'];r.uploadedIds=['e1','e2'];return r;};
const noop=async()=>{};
test('new installation is empty, English, wizard pending',()=>{const c=defaultConfig();assert.equal(c.rooms.length,0);assert.equal(c.language,'en');assert.equal(c.setupComplete,false);});
test('v0.3 migration retains addresses and associations',()=>{const c=migrateConfig({schema:2,rooms:[{id:'r1',name:'Sala 1',base:'192.168.50.113',hotelId:'home1',eventId:'event1',managedEventIds:['event1']}]});assert.equal(c.rooms[0].base,'http://192.168.50.113');assert.deepEqual(itemIds(c.rooms[0].playlists.home),['home1']);assert.equal(c.setupComplete,true);});
test('v0.1 migration infers temporary events conservatively',()=>{const c=migrateConfig({schema:1,rooms:[{id:'r1',name:'A',base:'x.local',hotelId:'h',eventId:'e',uploadedIds:['h','e','x']}]});assert.deepEqual(c.rooms[0].managedEventIds,['e']);});
test('numbers stay stable after delete and add',()=>{const c=defaultConfig();appendPlayer(c,'A','a.local');appendPlayer(c,'B','b.local');c.rooms.shift();const r=appendPlayer(c,'C','c.local');assert.equal(r.number,3);assert.equal(migrateConfig(c).rooms[0].number,2);});
test('schema roundtrip has no migration churn',()=>{const c=defaultConfig();appendPlayer(c,'Board room','board.local');assert.deepEqual(migrateConfig(migrateConfig(c)),migrateConfig(c));});
test('name limit permits 40 characters but rejects 41',()=>{assert.equal(normalizeName('a'.repeat(40)).length,40);assert.throws(()=>normalizeName('a'.repeat(41)));});
test('name migration truncates old name consistently',()=>assert.equal(normalizeName('a'.repeat(80),true).length,40));
test('duplicate addresses rejected',()=>{const c=defaultConfig();appendPlayer(c,'a','192.168.1.1');appendPlayer(c,'b','192.168.1.1');assert.throws(()=>migrateConfig(c));});
test('duplicate player numbers rejected',()=>{const c=defaultConfig();appendPlayer(c,'a','a');appendPlayer(c,'b','b');c.rooms[1].number=1;assert.throws(()=>migrateConfig(c));});
test('unsupported config rejected instead of reset',()=>assert.throws(()=>migrateConfig({schema:99,rooms:[]})));
test('overlapping roles rejected',()=>{const c=defaultConfig(),r=appendPlayer(c,'a','a');r.playlists={home:[{id:'x'}],event:[{id:'x'}]};assert.throws(()=>migrateConfig(c));});
test('portable export removes cleanup and wizard state',()=>{const c=defaultConfig(),r=appendPlayer(c,'a','a');r.cleanup=[{assetId:'x'}];c.wizardDraft=[{name:'x'}];const e=exportConfig(c);assert.equal(e.wizardDraft,null);assert.deepEqual(e.rooms[0].cleanup,[]);assert.equal('hmrAuthV4' in e,false);});
test('duration validation rejects invalid values',()=>{for(const duration of [0,-1,1.2,86401])assert.throws(()=>cleanItems([{id:'a',duration}]));});
test('duplicate playlist IDs rejected',()=>assert.throws(()=>cleanItems([{id:'a'},{id:'a'}])));
test('normalised endpoint does not allow embedded credentials',()=>{assert.equal(normalizeBase('192.168.1.2:8080'),'http://192.168.1.2:8080');assert.throws(()=>normalizeBase('http://user:pw@host'));assert.throws(()=>normalizeBase('file:///tmp'));});
test('exact host permission includes no port or path',()=>assert.equal(originPermission('http://host:8080'),'http://host/*'));
test('media preview uses dedicated endpoint',()=>assert.equal(mediaUrl('http://pi',file('h1')),'/ar/proxy?base=http%3A%2F%2Fpi&path=%2Fassets%2Fh1%2Fpreview%2F'));
test('file type rejects executable and arbitrary URL',()=>{assert.equal(fileKind({name:'FILE.MP4'}),'video');assert.throws(()=>fileKind({name:'x.exe'}));});
test('unready files cannot be published',()=>{const a=file('a');a.is_processing=true;assert.throws(()=>assertReady(a));});
test('multiasset publication sets order, image timings and exclusive membership',async()=>{const api=new API();await switchPlaylist(api,[{id:'e2',duration:null},{id:'e1',duration:23}]);assert(matchesActive(api.data,[{id:'e2'},{id:'e1'}]));assert.equal((await api.get('e1')).duration,23);assert.equal((await api.get('e2')).duration,42);});
test('video duration never receives the default image timer',async()=>{const api=new API();await switchPlaylist(api,[{id:'e2',duration:15}]);assert(!api.calls.some(c=>c[0]==='patch'&&c[1]==='e2'&&'duration'in c[2]));});
test('identical playlist triggers no writes or viewer jump',async()=>{const api=new API();const result=await switchPlaylist(api,[{id:'h1',duration:15}]);assert.equal(result.unchanged,true);assert.deepEqual(api.calls,[]);});
test('shuffle is disabled only on publication',async()=>{const api=new API();api.config.shuffle_playlist=true;await switchPlaylist(api,[{id:'e1',duration:15}]);assert.equal(api.config.shuffle_playlist,false);});
test('patch failure restores former active playlist and retains no false success',async()=>{const api=new API();api.fail='h1';let journal;await assert.rejects(switchPlaylist(api,[{id:'e1',duration:20}],{saveJournal:async j=>journal=copy(j)}));assert(matchesActive(api.data,[{id:'h1'}]));assert.equal((await api.get('e1')).duration,15);assert(journal.touched.includes('h1'));});
test('ordering verification detects wrong ordering and restores it',async()=>{const api=new API();api.orderWrong=true;await assert.rejects(switchPlaylist(api,[{id:'e2'},{id:'e1'}]));assert(matchesActive(api.data,[{id:'h1'}]));});
test('viewer jump failure is reported separately from playlist success',async()=>{const api=new API();api.controlFail=true;const result=await switchPlaylist(api,[{id:'e1'}]);assert(result.warning);assert(matchesActive(api.data,[{id:'e1'}]));});
test('empty playlist cannot be published',async()=>await assert.rejects(switchPlaylist(new API(),[])));
test('missing target validation occurs before writes',async()=>{const api=new API();await assert.rejects(switchPlaylist(api,[{id:'missing'}]));assert.deepEqual(api.calls,[]);});
test('last published mode survives prepared replacement',async()=>{const api=new API(),r=createRoom();await publishRoom(api,r,'event',{persist:noop});await mapPlaylist(r,'event',[{id:'next',duration:15}],api.data,noop);assert.equal(playlistState(api.data,r).role,'event');assert.deepEqual(itemIds(playlistState(api.data,r).items),['e1','e2']);});
test('staging a playlist does not change server playback',async()=>{const api=new API(),r=createRoom();await mapPlaylist(r,'home',[{id:'h2',duration:90}],api.data,noop);assert.deepEqual(api.calls,[]);assert.equal(playlistState(api.data,r).role,'home');assert.equal(r.lastPublished.items[0].id,'h1');});
test('event publication requires a Home fallback',async()=>{const api=new API(),r=createRoom();r.playlists.home=[];await assert.rejects(publishRoom(api,r,'event',{persist:noop}));assert.deepEqual(api.calls,[]);});
test('returning home queues all temporary event items',async()=>{const api=new API(),r=createRoom();await publishRoom(api,r,'event',{persist:noop});await publishRoom(api,r,'home',{persist:noop});assert.deepEqual(r.playlists.event,[]);assert.deepEqual(r.cleanup.map(j=>j.assetId).sort(),['e1','e2']);});
test('cleanup removes complete ended event playlist, not Home',async()=>{const api=new API(),r=createRoom();await publishRoom(api,r,'event',{persist:noop});await publishRoom(api,r,'home',{persist:noop});const result=await cleanupRoom(api,r,noop,{now:()=>Date.now()+6000});assert.equal(result.deleted.length,2);assert(await api.get('h1'));assert.equal(await api.get('e2'),undefined);});
test('cleanup also supports a multiasset Home target',async()=>{const api=new API(),r=createRoom();r.playlists.home=[{id:'h1',duration:15},{id:'h2',duration:20}];await publishRoom(api,r,'event',{persist:noop});await publishRoom(api,r,'home',{persist:noop});await cleanupRoom(api,r,noop,{now:()=>Date.now()+6000});assert(matchesActive(api.data,r.playlists.home));assert.equal(await api.get('e1'),undefined);});
test('auto-cleanup disabled retains event playlist for reuse',async()=>{const api=new API(),r=createRoom();await publishRoom(api,r,'event',{persist:noop,autoCleanup:false});await publishRoom(api,r,'home',{persist:noop,autoCleanup:false});assert.equal(r.playlists.event.length,2);assert.equal(r.cleanup.length,0);});
test('prepared next event is not deleted when the old event ends',async()=>{const api=new API(),r=createRoom();r.managedEventIds.push('next');await publishRoom(api,r,'event',{persist:noop});await mapPlaylist(r,'event',[{id:'next',duration:15}],api.data,noop);await publishRoom(api,r,'home',{persist:noop});assert.equal(r.playlists.event[0].id,'next');await cleanupRoom(api,r,noop,{now:()=>Date.now()+6000});assert(await api.get('next'));assert.equal(await api.get('e1'),undefined);});
test('reused library assets without ownership are retained',async()=>{const api=new API(),r=createRoom();r.managedEventIds=[];await publishRoom(api,r,'event',{persist:noop});await publishRoom(api,r,'home',{persist:noop});assert.equal(r.cleanup.length,0);assert(await api.get('e1'));});
test('unacknowledged viewer jump prevents automatic deletion queue',async()=>{const api=new API(),r=createRoom();await publishRoom(api,r,'event',{persist:noop});api.controlFail=true;await publishRoom(api,r,'home',{persist:noop});assert.equal(r.cleanup.length,0);});
test('external change suspends queued cleanup',async()=>{const api=new API(),r=createRoom();await publishRoom(api,r,'event',{persist:noop});await publishRoom(api,r,'home',{persist:noop});api.data.find(a=>a.asset_id==='next').is_enabled=true;api.data.find(a=>a.asset_id==='next').is_active=true;const out=await cleanupRoom(api,r,noop,{now:()=>Date.now()+6000});assert.equal(out.deleted.length,0);assert.equal(out.pending.length,2);});
test('shared physical path blocks deletion',()=>{const api=new API(),r=createRoom(),a=api.data.find(a=>a.asset_id==='next');api.data.push({...file('shared'),uri:a.uri});assert.match(deletionBlock(a,api.data,r),/shared/);});
test('Home history remains protected from automatic cleanup',()=>{const api=new API(),r=createRoom();r.homeHistory=['next'];r.managedEventIds.push('next');assert.match(deletionBlock(api.data.find(a=>a.asset_id==='next'),api.data,r,{automatic:true}),/Home/);});
test('legacy recovery format is still accepted',async()=>{const api=new API();await api.patch('h1',{is_enabled:false});const errors=await restoreJournal(api,{touched:['h1'],before:{h1:{is_enabled:true}}});assert.deepEqual(errors,[]);});
test('private range produces exact endpoints',()=>assert.deepEqual(scanTargets({start:'192.168.50.1',end:'192.168.50.3'}),['http://192.168.50.1','http://192.168.50.2','http://192.168.50.3']));
test('public, oversized and reversed scan ranges rejected',()=>{for(const r of [{start:'8.8.8.8',end:'8.8.8.9'},{start:'10.0.0.1',end:'10.0.5.1'},{start:'192.168.1.2',end:'192.168.1.1'}])assert.throws(()=>scanTargets(r));});
test('invalid IPv4 and ports rejected',()=>{assert.throws(()=>ipv4('300.1.2.3'));assert.throws(()=>scanTargets({start:'10.0.0.1',end:'10.0.0.2',port:0}));assert.equal(ipString(ipv4('192.168.50.113')),'192.168.50.113');});
test('discovery requires an Anthias version and device model',()=>{assert(!isAnthiasInfo({version:'printer'}));assert(!isAnthiasInfo({anthias_version:'x'}));assert(isAnthiasInfo({anthias_version:'v2026.9.0',device_model:'Pi'}));});
test('discovery identifies configured and moved Balena players',()=>{const players=[{base:'http://a',identity:'balena:1'}];assert.equal(classifyResult({base:'http://a'},players).kind,'existing');assert.equal(classifyResult({base:'http://b',identity:'balena:1'},players).kind,'moved');assert.equal(classifyResult({base:'http://b',identity:''},players).kind,'new');});
test('scan bounds concurrency and deduplicates identities',async()=>{let active=0,max=0;const out=await scanPlayers(['a','b','c','d'],{concurrency:2,probe:async base=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;return {base,identity:base==='b'?'a':base};}});assert.equal(max,2);assert.equal(out.results.length,3);});
test('scan cancellation stops launching further probes',async()=>{const controller=new AbortController();let count=0;const out=await scanPlayers(['a','b','c'],{signal:controller.signal,concurrency:1,probe:async base=>{count++;controller.abort();return {base};}});assert.equal(count,1);assert.equal(out.stopped,true);});
test('English and Italian parameters render correctly',()=>{setLanguage('it');assert.equal(t('Player {number}',{number:7}),'Player 7');assert.equal(t('Home content'),'Contenuto base');setLanguage('en');assert.equal(t('Home content'),'Home content');});
test('cleanup rechecks the enabled setting before each deletion',async()=>{const api=new API(),r=createRoom();await publishRoom(api,r,'event',{persist:noop});await publishRoom(api,r,'home',{persist:noop});let enabled=true;const remove=api.remove.bind(api);api.remove=async id=>{await remove(id);enabled=false;};const out=await cleanupRoom(api,r,noop,{now:()=>Date.now()+6000,enabled:()=>enabled});assert.equal(out.deleted.length,1);assert.equal(r.cleanup.length,1);});
test('cleanup stops if disabled while waiting for asset verification',async()=>{const api=new API(),r=createRoom();await publishRoom(api,r,'event',{persist:noop});await publishRoom(api,r,'home',{persist:noop});let enabled=true;const assets=api.assets.bind(api);api.assets=async()=>{enabled=false;return assets();};const out=await cleanupRoom(api,r,noop,{now:()=>Date.now()+6000,enabled:()=>enabled});assert.equal(out.deleted.length,0);assert.equal(r.cleanup.length,2);});
