import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {homeSelectionBlock,homeMediaDraft} from '../web/media-library.js';
import {newRoom} from '../web/storage.js';
import {setLanguage} from '../web/i18n.js';
const room=()=>newRoom('Conference room','192.168.1.20');
const asset=(id='file',kind='image')=>({asset_id:id,mimetype:kind,uri:`/data/anthias_assets/${id}.${kind==='image'?'png':'mp4'}`,duration:15,is_processing:false,is_reachable:true,metadata:{}});
test('v0.5.1 ready local media can be selected for Home',()=>assert.equal(homeSelectionBlock(asset(),room()),''));
test('v0.5.1 already-in-draft files cannot be duplicated',()=>assert.match(homeSelectionBlock(asset(),room(),[{id:'file'}]),/already/));
test('v0.5.1 prepared Event files cannot be reused by Home',()=>{const r=room();r.playlists.event=[{id:'file'}];assert.match(homeSelectionBlock(asset(),r),/Event/);});
test('v0.5.1 live Event snapshot remains protected when next Event is prepared',()=>{const r=room();r.lastPublished={role:'event',items:[{id:'file'}]};r.playlists.event=[{id:'next'}];assert.match(homeSelectionBlock(asset(),r),/Event/);});
test('v0.5.1 files awaiting cleanup are not offered as new Home sources',()=>{const r=room();r.cleanup=[{assetId:'file'}];assert.match(homeSelectionBlock(asset(),r),/cleanup/);});
test('v0.5.1 unready and non-local media cannot be selected',()=>{const r=room();assert(homeSelectionBlock({...asset(),is_processing:true},r));assert(homeSelectionBlock({...asset(),uri:'https://example.com/file.png'},r));assert(homeSelectionBlock(null,r));});
test('v0.5.1 selection validation never mutates ownership, cleanup or assignments',()=>{const r=room(),before=structuredClone(r);homeSelectionBlock(asset(),r);assert.deepEqual(r,before);});
test('v0.5.1 active Home media can be reused when not duplicated',()=>{const r=room();r.lastPublished={role:'home',items:[{id:'file'}]};assert.equal(homeSelectionBlock({...asset(),is_active:true,is_enabled:true},r), '');});
test('v0.5.1 reuse keeps a saved valid image duration',()=>{const d=homeMediaDraft({...asset(),duration:32},15);assert.equal(d.duration,32);assert.equal(d.id,'file');assert.equal(d.file,null);assert.equal(d.kind,'image');});
test('v0.5.1 invalid image durations use configured default or 15 seconds',()=>{assert.equal(homeMediaDraft({...asset(),duration:0},20).duration,20);assert.equal(homeMediaDraft({...asset(),duration:0},0).duration,15);});
test('v0.5.1 reused videos keep to-end timing and unique draft keys',()=>{const a=homeMediaDraft(asset('v','video')),b=homeMediaDraft(asset('v','video'));assert.equal(a.duration,null);assert.equal(a.kind,'video');assert.notEqual(a.key,b.key);});
test('v0.5.1 media guards have Italian translations',()=>{setLanguage('it');try{const r=room();r.playlists.event=[{id:'file'}];assert.equal(homeSelectionBlock(asset(),r),'Assegnato all’evento.');}finally{setLanguage('en');}});
test('v0.5.1 public discovery examples use 192.168.1.0/24 without seeding a player',()=>{for(const name of ['panel.html','panel.js','i18n.js']){const source=fs.readFileSync(new URL('../web/'+name,import.meta.url),'utf8');assert(source.includes('192.168.1.0/24'));assert(!source.includes('192.168.50.0/24'));}});
